import pandas as pd


def evaluate_alerts(df: pd.DataFrame) -> None:
    """
    Evaluate how well the anomaly detection system performed.

    This function compares:
    - the true condition of the data (from simulation)
    - the predicted alerts (from our detection system)

    It calculates:
    - True Positives  (correctly detected problems)
    - False Positives (false alarms)
    - False Negatives (missed problems)
    - True Negatives  (correctly identified normal cases)

    It also computes:
    - Precision: how reliable the alerts are
    - Recall: how many real problems we successfully detected
    """

    # ---------------------------------------------------------------------
    # STEP 1: Convert labels into simple True/False values
    # ---------------------------------------------------------------------
    # True abnormal = anything that is not "normal"
    df["true_abnormal"] = df["status"] != "normal"

    # Predicted abnormal = any alert that is not "normal"
    df["predicted_abnormal"] = df["alert_level"] != "normal"

    # ---------------------------------------------------------------------
    # STEP 2: Build confusion matrix components
    # ---------------------------------------------------------------------
    # These are standard evaluation metrics used in classification problems.

    # True Positives:
    # Cases where there WAS a problem and we correctly detected it.
    tp = ((df["true_abnormal"]) & (df["predicted_abnormal"])).sum()

    # True Negatives:
    # Cases where everything was normal and we correctly did NOT raise an alert.
    tn = ((~df["true_abnormal"]) & (~df["predicted_abnormal"])).sum()

    # False Positives:
    # Cases where we raised an alert but there was actually no problem.
    # (False alarms)
    fp = ((~df["true_abnormal"]) & (df["predicted_abnormal"])).sum()

    # False Negatives:
    # Cases where there WAS a problem but we failed to detect it.
    # (Missed issues)
    fn = ((df["true_abnormal"]) & (~df["predicted_abnormal"])).sum()

    # ---------------------------------------------------------------------
    # STEP 3: Print confusion matrix results
    # ---------------------------------------------------------------------
    print("=== Detection Performance ===")
    print(f"True Positives  (correct alerts): {tp}")
    print(f"False Positives (false alarms):  {fp}")
    print(f"False Negatives (missed issues): {fn}")
    print(f"True Negatives  (correct normal): {tn}")

    # ---------------------------------------------------------------------
    # STEP 4: Calculate evaluation metrics
    # ---------------------------------------------------------------------

    # Precision:
    # Of all alerts we raised, how many were actually correct?
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0

    # Recall:
    # Of all real problems, how many did we successfully detect?
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0

    # ---------------------------------------------------------------------
    # STEP 5: Print metrics
    # ---------------------------------------------------------------------
    print("\n=== Metrics ===")
    print(f"Precision: {precision:.2f}")
    print(f"Recall:    {recall:.2f}")


def main():
    """
    Load the alert data and run evaluation.
    """

    # Read the file generated by detect_anomalies.py
    df = pd.read_csv("haul_truck_alerts.csv")

    # Run evaluation
    evaluate_alerts(df)


if __name__ == "__main__":
    main()